package it.msec.kio.ref

import assertk.assertThat
import assertk.assertions.isEqualTo
import it.msec.kio.common.tuple.T
import it.msec.kio.flatMap
import it.msec.kio.peek
import it.msec.kio.ref.Ref.Companion.ref
import it.msec.kio.unsafeRunSyncAndGet
import org.junit.Test

class RefTest {

    @Test
    fun `ref provides its value`() {
        val r = ref(33).flatMap { it.get() }.unsafeRunSyncAndGet()
        assertThat(r).isEqualTo(33)
    }

    @Test
    fun `ref value can be set`() {
        val r = ref(33).peek { it.set(44) }.flatMap { it.get() }.unsafeRunSyncAndGet()
        assertThat(r).isEqualTo(44)
    }

    @Test
    fun `ref value can be retrieved and updated atomically`() {
        val ref = ref(33).unsafeRunSyncAndGet()
        val r = ref.getAndUpdate { it * 2 }.unsafeRunSyncAndGet()
        val r2 = ref.get().unsafeRunSyncAndGet()
        assertThat(r).isEqualTo(33)
        assertThat(r2).isEqualTo(66)
    }

    @Test
    fun `ref value can be updated and then retrieved atomically`() {
        val r1 = ref(33).flatMap { r -> r.updateAndGet { it * 2 } }.unsafeRunSyncAndGet()
        assertThat(r1).isEqualTo(66)
    }

    @Test
    fun `ref modify applies the change and returns the generated output`() {
        val r1 = ref(33).flatMap { r -> r.modify { T(44, it / 3) } }.unsafeRunSyncAndGet()
        assertThat(r1).isEqualTo(11)
    }

    @Test
    fun `ref update changes the current value with the one generated by the argument function`() {
        val ref = ref(33).unsafeRunSyncAndGet()
        ref.update { it / 3 }.unsafeRunSyncAndGet()
        assertThat(ref.get().unsafeRunSyncAndGet()).isEqualTo(11)
    }
}
